version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: "ledger_app_1"
    volumes:
      - .:/ledger
    ports:
      - "7004:3000"
    networks:
      - ledger_network
    links:
      - db
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - postgres-data
    ports:
      - "5432:5432"
    networks:
      - ledger_network
    restart: unless-stopped

networks:
  ledger_network:

volumes:
  postgres-data:
